# /sauti-frontend/Dockerfile.dev

FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install --include=dev

# Expose the Vite dev server port
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host"]
