# Generated by Django 4.2.16 on 2025-10-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
