# Generated by Django 4.2.16 on 2026-01-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='PUBLISHED', max_length=10),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['status', 'language'], name='faqs_faq_status_247cd8_idx'),
        ),
    ]
