# Generated by Django 4.2.16 on 2026-07-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_feedbackmessage_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmessage',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
