# Generated by Django 4.2.16 on 2026-01-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('NEWS', 'News'), ('BLOG', 'Blog')], default='NEWS', help_text='Type of content: Official News or Blog/Story', max_length=10),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['post_type', '-published_at'], name='posts_post_post_ty_1cb1c1_idx'),
        ),
    ]
