# Generated by Django 4.2.16 on 2025-12-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='scheduled_publish_at',
            field=models.DateTimeField(blank=True, help_text='Schedule automatic publishing at this date/time', null=True),
        ),
    ]
