# Generated by Django 4.2.16 on 2026-07-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_historicalpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='secondary_image',
            field=models.TextField(blank=True, help_text='Optional second image shown within the article body', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='secondary_image',
            field=models.ImageField(blank=True, help_text='Optional second image shown within the article body', null=True, upload_to='posts/images/%Y/%m/'),
        ),
    ]
