# Generated by Django 4.2.16 on 2026-08-26 10:00
# Hand-written (no Django/DB available in this environment) -- mirrors the
# style of 0006_historicalpost_secondary_image_post_secondary_image.py.
# Needs `python manage.py makemigrations --check` + `migrate` run for real.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='featured_image_thumbnail',
            field=models.TextField(blank=True, editable=False, help_text='Auto-generated thumbnail derived from featured_image', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalpost',
            name='featured_image_medium',
            field=models.TextField(blank=True, editable=False, help_text='Auto-generated medium-size derivative of featured_image', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='featured_image_thumbnail',
            field=models.ImageField(blank=True, editable=False, help_text='Auto-generated thumbnail derived from featured_image', null=True, upload_to='posts/images/thumbnails/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='post',
            name='featured_image_medium',
            field=models.ImageField(blank=True, editable=False, help_text='Auto-generated medium-size derivative of featured_image', null=True, upload_to='posts/images/medium/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='image_thumbnail',
            field=models.ImageField(blank=True, editable=False, help_text='Auto-generated thumbnail derived from image', null=True, upload_to='posts/gallery/thumbnails/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='image_medium',
            field=models.ImageField(blank=True, editable=False, help_text='Auto-generated medium-size derivative of image', null=True, upload_to='posts/gallery/medium/%Y/%m/'),
        ),
    ]
