# Generated by Django 4.2.16 on 2025-12-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the service', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the service')),
                ('icon', models.CharField(blank=True, help_text="Name of the icon for the service (e.g., 'phone', 'walk-in')", max_length=50, null=True)),
                ('order', models.IntegerField(help_text='Order in which the service appears (lower numbers first)', unique=True)),
                ('is_visible', models.BooleanField(default=True, help_text='Whether this service should be visible')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
    ]
