# Generated by Django 4.2.16 on 2026-01-03 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('child-protection', 'Child Protection'), ('gbv', 'Gender Based Violence'), ('migrants', 'Migrant Workers'), ('psea', 'PSEA')], help_text='Unique key for the service URL', max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('intro_text', models.TextField(help_text='Introduction text for the service page')),
                ('scope_items', models.JSONField(blank=True, default=list, help_text='List of items covered by this service (JSON array of strings)')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Help Service',
                'verbose_name_plural': 'Help Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HelpStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('step_order', models.IntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='services.helpservice')),
            ],
            options={
                'verbose_name': 'Help Step',
                'verbose_name_plural': 'Help Steps',
                'ordering': ['step_order'],
            },
        ),
    ]
