# Generated by Django 4.2.16 on 2026-01-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_helpservice_created_by_helpservice_last_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpservice',
            options={'ordering': ['homepage_display_order', 'order'], 'verbose_name': 'Help Service', 'verbose_name_plural': 'Help Services'},
        ),
        migrations.AddField(
            model_name='helpservice',
            name='homepage_display_order',
            field=models.IntegerField(default=0, help_text='Order on the homepage'),
        ),
        migrations.AddField(
            model_name='helpservice',
            name='icon_name',
            field=models.CharField(default='ShieldCheckIcon', help_text='Heroicon name (e.g., UserGroupIcon)', max_length=50),
        ),
        migrations.AddField(
            model_name='helpservice',
            name='summary',
            field=models.TextField(blank=True, help_text='Short summary for the homepage card'),
        ),
    ]
