# Generated by Django 4.2.16 on 2026-01-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='PUBLISHED', max_length=10),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['status', '-published_at'], name='resources_r_status_b0b819_idx'),
        ),
    ]
