# Generated by Django 4.2.16 on 2025-12-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text="Year or specific date of the event (e.g., '2013', 'Aug 2013')", max_length=10)),
                ('title', models.CharField(help_text='Title of the timeline event', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the event')),
                ('order', models.IntegerField(help_text='Order in which the event appears on the timeline (lower numbers first)', unique=True)),
                ('is_visible', models.BooleanField(default=True, help_text='Whether this event should be visible on the timeline')),
            ],
            options={
                'verbose_name': 'Timeline Event',
                'verbose_name_plural': 'Timeline Events',
                'ordering': ['order', 'year'],
            },
        ),
    ]
