# Generated by Django 4.2.16 on 2026-01-03 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timeline', '0002_timelineevent_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTimelineEvent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('year', models.CharField(help_text="Year or specific date of the event (e.g., '2013', 'Aug 2013')", max_length=10)),
                ('title', models.CharField(help_text='Title of the timeline event', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the event')),
                ('order', models.IntegerField(db_index=True, help_text='Order in which the event appears on the timeline (lower numbers first)')),
                ('is_visible', models.BooleanField(default=True, help_text='Whether this event should be visible on the timeline')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Timeline Event',
                'verbose_name_plural': 'historical Timeline Events',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
