# Generated by Django 4.2.16 on 2025-12-22 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Video Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField(help_text='Video description')),
                ('video_type', models.CharField(choices=[('YOUTUBE', 'YouTube Video'), ('UPLOAD', 'Uploaded Video')], default='YOUTUBE', max_length=10)),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube video URL (e.g., https://www.youtube.com/watch?v=VIDEO_ID)', null=True)),
                ('video_file', models.FileField(blank=True, help_text='Upload video file (MP4, AVI, etc.)', null=True, upload_to='videos/files/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Video thumbnail image', null=True, upload_to='videos/thumbnails/%Y/%m/')),
                ('duration', models.DurationField(blank=True, help_text='Video duration', null=True)),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=10)),
                ('language', models.CharField(choices=[('en', 'English'), ('lg', 'Luganda'), ('sw', 'Swahili')], default='en', max_length=2)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature on homepage')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_publish_at', models.DateTimeField(blank=True, help_text='Schedule automatic publishing at this date/time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='videos.videocategory')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['-published_at'], name='videos_vide_publish_c5c637_idx'), models.Index(fields=['status', '-published_at'], name='videos_vide_status_d96df9_idx'), models.Index(fields=['video_type'], name='videos_vide_video_t_2e9eac_idx')],
            },
        ),
    ]
