# Generated by Django 4.2.16 on 2026-06-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_created_by_video_last_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_type',
            field=models.CharField(choices=[('YOUTUBE', 'YouTube Video'), ('UPLOAD', 'Uploaded Video'), ('AUDIO', 'Uploaded Audio')], default='YOUTUBE', max_length=10),
        ),
    ]
