# Generated by Django 4.2.16 on 2026-08-26 10:00
# Hand-written (no Django/DB available in this environment).
# Needs `python manage.py makemigrations --check` + `migrate` run for real.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_video_video_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_small',
            field=models.ImageField(blank=True, editable=False, help_text='Auto-generated small derivative of thumbnail', null=True, upload_to='videos/thumbnails/small/%Y/%m/'),
        ),
    ]
