from django.core import signing
from rest_framework import generics, permissions, filters
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.exceptions import PermissionDenied
from rest_framework.generics import get_object_or_404
from .models import Post, Category, Tag, PostImage
from .serializers import (
    PostListSerializer, PostDetailSerializer, PostCreateUpdateSerializer,
    CategorySerializer, TagSerializer, PostImageSerializer
)


class IsEditorOrReadOnly(permissions.BasePermission):
    """
    Read-only for everyone; writes require the view's `required_permission`
    codename (checked dynamically via User.has_permission -- see
    users/models.py's Role/Permission system). Defaults to 'create_posts',
    the same bundle (Author/Editor/Admin) the old hardcoded is_author check
    granted, so importing this class with no override reproduces prior
    behavior exactly.
    """
    required_permission = 'create_posts'

    def has_permission(self, request, view):
        if request.method in permissions.SAFE_METHODS:
            return True
        codename = getattr(view, 'required_permission', self.required_permission)
        return request.user.is_authenticated and request.user.has_permission(codename)


class PostListCreateView(generics.ListCreateAPIView):
    """
    GET /api/posts/ - List all published posts (or all for authenticated editors)
    POST /api/posts/ - Create new post (Editors/Admins only)
    """
    permission_classes = [IsEditorOrReadOnly]
    filter_backends = [filters.SearchFilter, filters.OrderingFilter]
    search_fields = ['title', 'content', 'excerpt']
    ordering_fields = ['published_at', 'created_at', 'views_count']
    ordering = ['-published_at']
    
    def get_queryset(self):
        queryset = Post.objects.select_related('author', 'category').prefetch_related('tags')
        
        # Public users see only published posts
        if not self.request.user.is_authenticated or not self.request.user.has_permission('manage_posts'):
            queryset = queryset.filter(status=Post.Status.PUBLISHED)
        
        # Filter by category
        category = self.request.query_params.get('category')
        if category:
            queryset = queryset.filter(category__slug=category)
        
        # Filter by language
        language = self.request.query_params.get('language')
        if language:
            queryset = queryset.filter(language=language)
        
        # Filter by featured
        is_featured = self.request.query_params.get('featured')
        if is_featured:
            queryset = queryset.filter(is_featured=True)
        
        # Filter by status
        status = self.request.query_params.get('status')
        if status:
            queryset = queryset.filter(status=status)
            
        # Filter by post_type
        post_type = self.request.query_params.get('post_type')
        if post_type:
            queryset = queryset.filter(post_type=post_type)
        
        return queryset
    
    def get_serializer_class(self):
        if self.request.method == 'POST':
            return PostCreateUpdateSerializer
        return PostListSerializer
    
    def perform_create(self, serializer):
        serializer.save(
            author=self.request.user,
            created_by=self.request.user,
            last_updated_by=self.request.user
        )


class PostDetailView(generics.RetrieveUpdateDestroyAPIView):
    """
    GET /api/posts/<slug>/ - Get post detail
    PUT/PATCH /api/posts/<slug>/ - Update post (Editors/Admins only)
    DELETE /api/posts/<slug>/ - Delete post (Admins only)
    """
    lookup_field = 'slug'
    permission_classes = [IsEditorOrReadOnly]
    
    def get_queryset(self):
        queryset = Post.objects.select_related('author', 'category').prefetch_related('tags')

        can_manage = self.request.user.is_authenticated and self.request.user.has_permission('manage_posts')
        if not can_manage and not self._has_valid_preview_token():
            queryset = queryset.filter(status=Post.Status.PUBLISHED)

        return queryset

    def _has_valid_preview_token(self):
        """
        The admin's Preview modal loads the public page in an anonymous
        iframe, so a draft (the whole point of previewing before it's
        published) 404'd -- the public queryset above only ever showed
        published posts. A short-lived signed token, generated by
        PostPreviewTokenView for one specific post, lets that one anonymous
        request through without opening drafts to the public generally.
        """
        token = self.request.query_params.get('preview_token')
        if not token:
            return False
        try:
            data = signing.loads(token, salt='post-preview', max_age=300)
        except signing.BadSignature:
            return False
        return str(data.get('slug')) == str(self.kwargs.get(self.lookup_url_kwarg or self.lookup_field))
    
    def get_serializer_class(self):
        if self.request.method in ['PUT', 'PATCH']:
            return PostCreateUpdateSerializer
        return PostDetailSerializer
    
    def retrieve(self, request, *args, **kwargs):
        instance = self.get_object()
        # Increment view count
        instance.views_count += 1
        instance.save(update_fields=['views_count'])
        serializer = self.get_serializer(instance)
        return Response(serializer.data)
        
    def perform_update(self, serializer):
        serializer.save(last_updated_by=self.request.user)


class PostImageListCreateView(generics.ListCreateAPIView):
    """
    GET  /api/posts/<int:post_id>/images/ - List gallery images for a post (ordered)
    POST /api/posts/<int:post_id>/images/ - Add a gallery image (Editors/Admins only, multipart)
    """
    serializer_class = PostImageSerializer
    permission_classes = [IsEditorOrReadOnly]

    def get_queryset(self):
        return PostImage.objects.filter(post_id=self.kwargs['post_id']).order_by('order', 'id')

    def perform_create(self, serializer):
        post = get_object_or_404(Post, pk=self.kwargs['post_id'])
        # Append new images to the end of the gallery unless an explicit order was given.
        next_order = PostImage.objects.filter(post=post).count()
        order = serializer.validated_data.get('order') or next_order
        serializer.save(post=post, order=order)


class PostImageDetailView(generics.RetrieveUpdateDestroyAPIView):
    """
    GET/PATCH/PUT/DELETE /api/posts/<int:post_id>/images/<int:pk>/
    Used to edit a gallery image's caption/alt text/order, or remove it.
    """
    serializer_class = PostImageSerializer
    permission_classes = [IsEditorOrReadOnly]

    def get_queryset(self):
        return PostImage.objects.filter(post_id=self.kwargs['post_id'])


class CategoryListView(generics.ListCreateAPIView):
    """
    GET /api/posts/categories/ - List categories
    POST /api/posts/categories/ - Create category (Editors/Admins only)
    """
    queryset = Category.objects.all()
    serializer_class = CategorySerializer
    permission_classes = [IsEditorOrReadOnly]


class CategoryDetailView(generics.RetrieveUpdateDestroyAPIView):
    """
    GET /api/posts/categories/<id>/ - Get category
    PUT/PATCH /api/posts/categories/<id>/ - Update category (Editors/Admins only)
    DELETE /api/posts/categories/<id>/ - Delete category (Editors/Admins only)
    """
    queryset = Category.objects.all()
    serializer_class = CategorySerializer
    permission_classes = [IsEditorOrReadOnly]


class TagListView(generics.ListCreateAPIView):
    """
    GET /api/posts/tags/ - List tags
    POST /api/posts/tags/ - Create tag (Editors/Admins only)
    """
    queryset = Tag.objects.all()
    serializer_class = TagSerializer
    permission_classes = [IsEditorOrReadOnly]


class PostPreviewTokenView(APIView):
    """
    GET /api/posts/<slug>/preview-token/ -- Editors/Admins only. Issues a
    5-minute signed token for exactly this post's slug, which the public
    PostDetailView accepts (see _has_valid_preview_token) to show a draft to
    the admin's anonymous Preview-modal iframe without exposing it publicly.
    """
    permission_classes = [permissions.IsAuthenticated]

    def get(self, request, slug):
        if not request.user.has_permission('manage_posts'):
            raise PermissionDenied('Only Editors and Admins can preview posts.')
        get_object_or_404(Post, slug=slug)
        token = signing.dumps({'slug': slug}, salt='post-preview')
        return Response({'token': token})
