# Generated by Django 4.2.16 on 2025-10-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, help_text='Partner logo', null=True, upload_to='partners/logos/'),
        ),
    ]
