# Generated by Django 4.2.16 on 2026-01-03 10:47

from django.db import migrations, models
import partners.models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_historicalpartner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, help_text='Partner logo', null=True, upload_to=partners.models.partner_logo_path),
        ),
    ]
