# Generated by Django 4.2.16 on 2026-07-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_alter_partner_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpartner',
            name='partner_type',
            field=models.CharField(choices=[('GOVERNMENT', 'Government Agency'), ('UN_AGENCY', 'UN Agency'), ('NGO', 'NGO/CSO'), ('EMBASSY', 'Embassy / Diplomatic Mission'), ('PRIVATE', 'Private Sector'), ('OTHER', 'Other')], default='NGO', max_length=15),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('GOVERNMENT', 'Government Agency'), ('UN_AGENCY', 'UN Agency'), ('NGO', 'NGO/CSO'), ('EMBASSY', 'Embassy / Diplomatic Mission'), ('PRIVATE', 'Private Sector'), ('OTHER', 'Other')], default='NGO', max_length=15),
        ),
    ]
