# Generated by Django 4.2.16 on 2026-07-22 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_alter_historicalpartner_partner_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpartner',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='PartnerPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='partners.partner')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
