# Generated by Django 4.2.16 on 2026-08-26 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_alter_historicalpartner_phone_alter_partner_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('order', models.PositiveIntegerField(default=0)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='partners.partner')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
