# Generated by Django 4.2.16 on 2026-08-26 10:00
# Hand-written (no Django/DB available in this environment) -- mirrors the
# style of 0006_alter_historicalpartner_phone_alter_partner_phone_and_more.py.
# Needs `python manage.py makemigrations --check` + `migrate` run for real.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_partneremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpartner',
            name='logo_thumbnail',
            field=models.TextField(blank=True, editable=False, help_text='Auto-generated thumbnail derived from logo', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='logo_thumbnail',
            field=models.ImageField(blank=True, editable=False, help_text='Auto-generated thumbnail derived from logo', null=True, upload_to='partners/logos/thumbnails/'),
        ),
    ]
