# Generated by Django 4.2.16 on 2025-12-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home Page'), ('about', 'About Page'), ('contact', 'Contact Page')], default='home', help_text='The page this setting belongs to.', max_length=50)),
                ('key', models.CharField(help_text="Unique identifier for the setting (e.g., 'hero_title').", max_length=255, unique=True)),
                ('value', models.TextField(blank=True, help_text='The configurable content for this setting.')),
                ('description', models.TextField(blank=True, help_text='A brief explanation of what this setting controls.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
                'ordering': ['page', 'key'],
                'unique_together': {('page', 'key')},
            },
        ),
    ]
