# Generated by Django 4.2.16 on 2026-01-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsettings',
            name='card_faqs_text',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='card_faqs_title',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='card_partners_text',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='card_partners_title',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='card_report_text',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='card_report_title',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='card_resources_text',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='card_resources_title',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='final_cta_call',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='final_cta_contact',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='final_cta_report',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='final_cta_text',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='final_cta_title',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='hero_cta_call',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='hero_cta_report',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='journey_description',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='journey_title',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='publications_description',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='publications_link',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='publications_title',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='resources_cases_by_category',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='resources_child_protection',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='resources_closed',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='resources_gbv_cases',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='resources_in_progress',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='resources_interactive',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='resources_last_6_months',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='resources_migrant_worker',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='resources_pending',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='resources_reports_over_time',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='resources_resolved',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='resources_stats_error',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='resources_stats_loading',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='resources_status_distribution',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='resources_total_reports',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='trust_partners_description',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='trust_partners_title',
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='hero_value_prop',
            field=models.TextField(blank=True, help_text='Short 1-2 line value proposition'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='hotline_number',
            field=models.CharField(default='116', max_length=20),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='intro_description',
            field=models.TextField(blank=True, help_text='Short description of who Sauti is and what it does'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='intro_title',
            field=models.CharField(blank=True, default='Who We Are', max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='news_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='news_link_text',
            field=models.CharField(blank=True, default='View All Articles', max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='news_title',
            field=models.CharField(blank=True, default='Latest News & Stories', max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='partners_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='partners_title',
            field=models.CharField(blank=True, default='Our Partners', max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='primary_cta_text',
            field=models.CharField(default='Get Help Now', max_length=50),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='privacy_policy_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='qa_child_protection_icon',
            field=models.CharField(default='UserGroupIcon', max_length=50),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='qa_child_protection_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='qa_child_protection_title',
            field=models.CharField(default='Child Protection', max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='qa_gbv_icon',
            field=models.CharField(default='ShieldCheckIcon', max_length=50),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='qa_gbv_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='qa_gbv_title',
            field=models.CharField(default='GBV Support', max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='qa_migrants_icon',
            field=models.CharField(default='GlobeAltIcon', max_length=50),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='qa_migrants_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='qa_migrants_title',
            field=models.CharField(default='Migrant Workers', max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='qa_psea_icon',
            field=models.CharField(default='ScaleIcon', max_length=50),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='qa_psea_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='qa_psea_title',
            field=models.CharField(default='PSEA', max_length=255),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='environment_label',
            field=models.CharField(blank=True, help_text="e.g., 'Development', 'Staging', 'Production'.", max_length=50),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='hotline_text',
            field=models.CharField(blank=True, help_text='Text displayed next to hotline number', max_length=255),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='quick_access_title',
            field=models.CharField(blank=True, default='How Can We Help?', max_length=255),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='site_name',
            field=models.CharField(default='Sauti 116', max_length=255),
        ),
    ]
