# Generated by Django 4.2.16 on 2025-12-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='key',
            field=models.CharField(help_text="Unique identifier for the setting (e.g., 'hero_title').", max_length=255),
        ),
    ]
