# Generated by Django 4.2.16 on 2025-12-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Sauti', max_length=255)),
                ('site_description', models.TextField(blank=True)),
                ('hotline_text', models.CharField(blank=True, max_length=255)),
                ('support_email_text', models.CharField(blank=True, max_length=255)),
                ('operating_hours_text', models.CharField(blank=True, max_length=255)),
                ('footer_text', models.TextField(blank=True)),
                ('ministry_attribution_text', models.TextField(blank=True)),
                ('disclaimer_text', models.TextField(blank=True)),
                ('default_meta_title_suffix', models.CharField(blank=True, max_length=255)),
                ('default_meta_description', models.TextField(blank=True)),
                ('environment_label', models.CharField(blank=True, help_text="e.g., 'Development', 'Staging', 'Production'. Will be displayed in the admin UI.", max_length=50)),
            ],
            options={
                'verbose_name': 'Global Settings',
                'verbose_name_plural': 'Global Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'ordering': ['page', 'key'], 'verbose_name': 'Site Setting (Deprecated)', 'verbose_name_plural': 'Site Settings (Deprecated)'},
        ),
    ]
