# Generated by Django 4.2.16 on 2026-01-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0002_remove_globalsettings_card_faqs_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='mission',
            field=models.TextField(blank=True, help_text="Organization's mission statement."),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='vision',
            field=models.TextField(blank=True, help_text="Organization's vision statement."),
        ),
    ]
