# Generated by Django 4.2.16 on 2025-12-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0003_globalsettings_alter_sitesetting_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='card_faqs_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='card_faqs_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='card_partners_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='card_partners_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='card_report_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='card_report_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='card_resources_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='card_resources_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='contact_email_info',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='contact_email_sautichl',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='contact_phone_main',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='contact_website',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='final_cta_call',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='final_cta_contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='final_cta_report',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='final_cta_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='final_cta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='hero_cta_call',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='hero_cta_report',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='hero_subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='hero_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='journey_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='journey_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='publications_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='publications_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='publications_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='quick_access_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='quick_access_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='social_facebook',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='social_safepal',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='social_twitter',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='social_ureport',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='social_whatsapp',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='trust_partners_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='trust_partners_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
