# Generated by Django 4.2.16 on 2026-01-02 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0003_globalsettings_mission_globalsettings_vision'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'About Page Settings',
                'verbose_name_plural': 'About Page Settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sitesettings.globalsettings',),
        ),
        migrations.CreateModel(
            name='HomePageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Home Page Settings',
                'verbose_name_plural': 'Home Page Settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sitesettings.globalsettings',),
        ),
    ]
