# Generated by Django 4.2.16 on 2025-12-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0004_globalsettings_card_faqs_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='resources_all_categories',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='resources_all_languages',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='resources_available',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='resources_cases_by_category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='resources_child_protection',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='resources_closed',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='resources_coming_soon',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='resources_downloads_subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='resources_downloads_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='resources_gbv_cases',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='resources_in_progress',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='resources_interactive',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='resources_last_6_months',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='resources_loading',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='resources_migrant_worker',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='resources_next',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='resources_no_results',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='resources_no_results_subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='resources_pending',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='resources_previous',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='resources_reports_over_time',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='resources_resolved',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='resources_search_placeholder',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='resources_stats_error',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='resources_stats_loading',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='resources_stats_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='resources_stats_updated',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='resources_status_distribution',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='resources_subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='resources_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='resources_total_reports',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
