# Generated by Django 4.2.16 on 2026-01-02 13:04

from django.db import migrations, models
import sitesettings.models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0004_aboutpagesettings_homepagesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='hero_badges',
            field=models.JSONField(blank=True, default=sitesettings.models.GlobalSettings.default_hero_badges, help_text="List of hero badges. Each badge should have 'label', 'color' (blue, orange, teal), and 'is_active'."),
        ),
    ]
