# Generated by Django 4.2.16 on 2026-01-03 07:02

from django.db import migrations, models
import sitesettings.models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0005_globalsettings_hero_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='footer_links',
            field=models.JSONField(blank=True, default=sitesettings.models.GlobalSettings.default_footer_links, help_text="List of footer links. Each link should have 'label', 'to' (URL path), and 'type' ('nav' or 'legal')."),
        ),
    ]
