# Generated by Django 4.2.16 on 2026-01-03 07:06

from django.db import migrations, models
import sitesettings.models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0006_globalsettings_footer_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='impact_stats',
            field=models.JSONField(blank=True, default=sitesettings.models.GlobalSettings.default_impact_stats, help_text="List of impact statistics. Each stat should have 'label', 'value', 'order', and 'is_active'."),
        ),
    ]
