# Generated by Django 4.2.16 on 2026-01-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0008_historicalglobalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='social_instagram',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='social_linkedin',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='social_tiktok',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='social_youtube',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalglobalsettings',
            name='social_instagram',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalglobalsettings',
            name='social_linkedin',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalglobalsettings',
            name='social_tiktok',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalglobalsettings',
            name='social_youtube',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
