# Generated by Django 4.2.16 on 2026-01-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0009_globalsettings_social_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='office_address',
            field=models.TextField(blank=True, help_text='Physical office address.'),
        ),
        migrations.AddField(
            model_name='historicalglobalsettings',
            name='office_address',
            field=models.TextField(blank=True, help_text='Physical office address.'),
        ),
    ]
