# Generated by Django 4.2.16 on 2026-01-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0010_globalsettings_office_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='accessibility_url',
            field=models.URLField(blank=True, help_text='Link to accessibility statement', max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='terms_of_service_url',
            field=models.URLField(blank=True, help_text='Link to terms of service page', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalglobalsettings',
            name='accessibility_url',
            field=models.URLField(blank=True, help_text='Link to accessibility statement', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalglobalsettings',
            name='terms_of_service_url',
            field=models.URLField(blank=True, help_text='Link to terms of service page', max_length=255),
        ),
    ]
