# Generated by Django 4.2.16 on 2026-01-04 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitesettings', '0012_remove_globalsettings_qa_child_protection_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sauti 116', max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org/identity/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='org/identity/')),
                ('primary_color', models.CharField(default='#C8102E', help_text='Primary brand color (Hex code, e.g., #C8102E)', max_length=7)),
                ('secondary_color', models.CharField(default='#003366', help_text='Secondary brand color (Hex code, e.g., #003366)', max_length=7)),
                ('accent_color', models.CharField(default='#FFB81C', help_text='Accent color (Hex code, e.g., #FFB81C)', max_length=7)),
                ('address', models.TextField(blank=True)),
                ('primary_phone', models.CharField(blank=True, max_length=20)),
                ('primary_email', models.EmailField(blank=True, max_length=254)),
                ('alternate_email', models.EmailField(blank=True, max_length=254)),
                ('registration_info', models.TextField(blank=True, help_text='Legal registration details')),
                ('founded_date', models.DateField(blank=True, null=True)),
                ('about_us_summary', models.TextField(blank=True, help_text="A short summary of the organization's identity")),
                ('twitter_handle', models.CharField(blank=True, max_length=50)),
                ('facebook_page', models.CharField(blank=True, max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization Profile',
                'verbose_name_plural': 'Organization Profile',
            },
        ),
        migrations.CreateModel(
            name='HistoricalOrganizationProfile',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(default='Sauti 116', max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('logo', models.TextField(blank=True, max_length=100, null=True)),
                ('favicon', models.TextField(blank=True, max_length=100, null=True)),
                ('primary_color', models.CharField(default='#C8102E', help_text='Primary brand color (Hex code, e.g., #C8102E)', max_length=7)),
                ('secondary_color', models.CharField(default='#003366', help_text='Secondary brand color (Hex code, e.g., #003366)', max_length=7)),
                ('accent_color', models.CharField(default='#FFB81C', help_text='Accent color (Hex code, e.g., #FFB81C)', max_length=7)),
                ('address', models.TextField(blank=True)),
                ('primary_phone', models.CharField(blank=True, max_length=20)),
                ('primary_email', models.EmailField(blank=True, max_length=254)),
                ('alternate_email', models.EmailField(blank=True, max_length=254)),
                ('registration_info', models.TextField(blank=True, help_text='Legal registration details')),
                ('founded_date', models.DateField(blank=True, null=True)),
                ('about_us_summary', models.TextField(blank=True, help_text="A short summary of the organization's identity")),
                ('twitter_handle', models.CharField(blank=True, max_length=50)),
                ('facebook_page', models.CharField(blank=True, max_length=100)),
                ('last_updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Organization Profile',
                'verbose_name_plural': 'historical Organization Profile',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
