# Generated by Django 4.2.16 on 2026-01-04 20:53

from django.db import migrations, models
import sitesettings.models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0013_organizationprofile_historicalorganizationprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganizationprofile',
            name='brand_colors',
            field=models.JSONField(blank=True, default=sitesettings.models.OrganizationProfile.default_brand_colors, help_text='Configurable brand colors with defaults.'),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='brand_colors',
            field=models.JSONField(blank=True, default=sitesettings.models.OrganizationProfile.default_brand_colors, help_text='Configurable brand colors with defaults.'),
        ),
        migrations.AlterField(
            model_name='historicalorganizationprofile',
            name='accent_color',
            field=models.CharField(default='#FF9933', help_text='Accent color (Hex code, e.g., #FF9933)', max_length=7),
        ),
        migrations.AlterField(
            model_name='historicalorganizationprofile',
            name='primary_color',
            field=models.CharField(default='#007BBF', help_text='Primary brand color (Hex code, e.g., #007BBF)', max_length=7),
        ),
        migrations.AlterField(
            model_name='historicalorganizationprofile',
            name='secondary_color',
            field=models.CharField(default='#006633', help_text='Secondary brand color (Hex code, e.g., #006633)', max_length=7),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='accent_color',
            field=models.CharField(default='#FF9933', help_text='Accent color (Hex code, e.g., #FF9933)', max_length=7),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='primary_color',
            field=models.CharField(default='#007BBF', help_text='Primary brand color (Hex code, e.g., #007BBF)', max_length=7),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='secondary_color',
            field=models.CharField(default='#006633', help_text='Secondary brand color (Hex code, e.g., #006633)', max_length=7),
        ),
    ]
