# Generated by Django 4.2.16 on 2026-02-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0014_historicalorganizationprofile_brand_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganizationprofile',
            name='team_photo',
            field=models.TextField(blank=True, help_text='A group photo of the organization team.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='team_photo',
            field=models.ImageField(blank=True, help_text='A group photo of the organization team.', null=True, upload_to='org/identity/'),
        ),
    ]
