# Generated by Django 4.2.16 on 2026-03-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0015_historicalorganizationprofile_team_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganizationprofile',
            name='about_hero_image_1',
            field=models.TextField(blank=True, help_text='About hero grid: Left column, top image (Community)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalorganizationprofile',
            name='about_hero_image_2',
            field=models.TextField(blank=True, help_text='About hero grid: Left column, middle image (Helpline)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalorganizationprofile',
            name='about_hero_image_3',
            field=models.TextField(blank=True, help_text='About hero grid: Left column, bottom image (Family)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalorganizationprofile',
            name='about_hero_image_4',
            field=models.TextField(blank=True, help_text='About hero grid: Center, top-right (Happy Students)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalorganizationprofile',
            name='about_hero_image_5',
            field=models.TextField(blank=True, help_text='About hero grid: Center, bottom-left (Action)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalorganizationprofile',
            name='about_hero_image_6',
            field=models.TextField(blank=True, help_text='About hero grid: Center, bottom-right (Protection)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalorganizationprofile',
            name='about_hero_image_7',
            field=models.TextField(blank=True, help_text='About hero grid: Right column, top image (Operations)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalorganizationprofile',
            name='about_hero_image_8',
            field=models.TextField(blank=True, help_text='About hero grid: Right column, middle image (Inclusive)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='about_hero_image_1',
            field=models.ImageField(blank=True, help_text='About hero grid: Left column, top image (Community)', null=True, upload_to='org/about/'),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='about_hero_image_2',
            field=models.ImageField(blank=True, help_text='About hero grid: Left column, middle image (Helpline)', null=True, upload_to='org/about/'),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='about_hero_image_3',
            field=models.ImageField(blank=True, help_text='About hero grid: Left column, bottom image (Family)', null=True, upload_to='org/about/'),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='about_hero_image_4',
            field=models.ImageField(blank=True, help_text='About hero grid: Center, top-right (Happy Students)', null=True, upload_to='org/about/'),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='about_hero_image_5',
            field=models.ImageField(blank=True, help_text='About hero grid: Center, bottom-left (Action)', null=True, upload_to='org/about/'),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='about_hero_image_6',
            field=models.ImageField(blank=True, help_text='About hero grid: Center, bottom-right (Protection)', null=True, upload_to='org/about/'),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='about_hero_image_7',
            field=models.ImageField(blank=True, help_text='About hero grid: Right column, top image (Operations)', null=True, upload_to='org/about/'),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='about_hero_image_8',
            field=models.ImageField(blank=True, help_text='About hero grid: Right column, middle image (Inclusive)', null=True, upload_to='org/about/'),
        ),
    ]
