# Generated by Django 4.2.16 on 2025-12-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('TikTok', 'TikTok'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn'), ('YouTube', 'YouTube')], max_length=50, verbose_name='Platform')),
                ('handle', models.CharField(help_text='e.g. @sauti116', max_length=100, verbose_name='Handle/Username')),
                ('content', models.TextField(blank=True, verbose_name='Content/Caption')),
                ('image', models.ImageField(blank=True, null=True, upload_to='social_media/', verbose_name='Image')),
                ('video_url', models.URLField(blank=True, help_text='Optional link to video', null=True, verbose_name='Video URL')),
                ('post_url', models.URLField(blank=True, help_text='Link to the original post', null=True, verbose_name='Post URL')),
                ('likes_count', models.CharField(default='0', help_text='e.g. 1.2k', max_length=20, verbose_name='Likes Count')),
                ('comments_count', models.CharField(default='0', help_text='e.g. 45', max_length=20, verbose_name='Comments Count')),
                ('shares_count', models.CharField(default='0', help_text='e.g. 12', max_length=20, verbose_name='Shares Count')),
                ('posted_at', models.DateTimeField(help_text='When was this posted on social media?', verbose_name='Posted At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Order in carousel')),
            ],
            options={
                'verbose_name': 'Social Media Post',
                'verbose_name_plural': 'Social Media Posts',
                'ordering': ['order', '-posted_at'],
            },
        ),
    ]
