# Generated by Django 4.2.16 on 2025-12-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_email', models.EmailField(blank=True, help_text='Main contact email (e.g., info@sauti.org)', max_length=254, null=True, verbose_name='Primary Email')),
                ('support_email', models.EmailField(blank=True, help_text='Support/help email (e.g., support@sauti.org)', max_length=254, null=True, verbose_name='Support Email')),
                ('primary_phone', models.CharField(blank=True, help_text='Main contact phone (e.g., +256 116 or 116)', max_length=50, null=True, verbose_name='Primary Phone')),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp contact number', max_length=50, null=True, verbose_name='WhatsApp Number')),
                ('office_address', models.TextField(blank=True, help_text='Physical office address', null=True, verbose_name='Office Address')),
                ('facebook_url', models.URLField(blank=True, help_text='Link to Facebook page', null=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, help_text='Link to Twitter/X profile', null=True, verbose_name='Twitter URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Link to Instagram profile', null=True, verbose_name='Instagram URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='Link to LinkedIn page', null=True, verbose_name='LinkedIn URL')),
                ('youtube_url', models.URLField(blank=True, help_text='Link to YouTube channel', null=True, verbose_name='YouTube URL')),
                ('tiktok_url', models.URLField(blank=True, help_text='Link to TikTok profile', null=True, verbose_name='TikTok URL')),
                ('working_hours', models.CharField(blank=True, help_text='e.g., 24/7 or Mon-Fri 8AM-5PM', max_length=100, null=True, verbose_name='Working Hours')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaChannels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_1_url', models.URLField(blank=True, help_text='Paste the link to your first social media post (TikTok, YouTube, Twitter, etc.)', null=True, verbose_name='Channel 1 URL')),
                ('channel_2_url', models.URLField(blank=True, help_text='Paste the link to your second social media post', null=True, verbose_name='Channel 2 URL')),
                ('channel_3_url', models.URLField(blank=True, help_text='Paste the link to your third social media post', null=True, verbose_name='Channel 3 URL')),
                ('channel_4_url', models.URLField(blank=True, help_text='Paste the link to your fourth social media post', null=True, verbose_name='Channel 4 URL')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Social Media Channels',
                'verbose_name_plural': 'Social Media Channels',
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('TikTok', 'TikTok'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn'), ('YouTube', 'YouTube')], max_length=50, verbose_name='Platform')),
                ('handle', models.CharField(help_text='e.g. @sauti116', max_length=100, verbose_name='Handle/Username')),
                ('content', models.TextField(blank=True, verbose_name='Content/Caption')),
                ('image', models.ImageField(blank=True, null=True, upload_to='social_media/', verbose_name='Image')),
                ('video_url', models.URLField(blank=True, help_text='Optional link to video', null=True, verbose_name='Video URL')),
                ('post_url', models.URLField(blank=True, help_text='Link to the original post', null=True, verbose_name='Post URL')),
                ('likes_count', models.CharField(default='0', help_text='e.g. 1.2k', max_length=20, verbose_name='Likes Count')),
                ('comments_count', models.CharField(default='0', help_text='e.g. 45', max_length=20, verbose_name='Comments Count')),
                ('shares_count', models.CharField(default='0', help_text='e.g. 12', max_length=20, verbose_name='Shares Count')),
                ('posted_at', models.DateTimeField(help_text='When was this posted on social media?', verbose_name='Posted At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Order in carousel')),
            ],
            options={
                'verbose_name': 'Social Media Post',
                'verbose_name_plural': 'Social Media Posts',
                'ordering': ['order', '-posted_at'],
            },
        ),
    ]
