# Generated by Django 4.2.16 on 2025-12-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaChannels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_1_url', models.URLField(blank=True, help_text='Paste the link to your first social media post (TikTok, YouTube, Twitter, etc.)', null=True, verbose_name='Channel 1 URL')),
                ('channel_2_url', models.URLField(blank=True, help_text='Paste the link to your second social media post', null=True, verbose_name='Channel 2 URL')),
                ('channel_3_url', models.URLField(blank=True, help_text='Paste the link to your third social media post', null=True, verbose_name='Channel 3 URL')),
                ('channel_4_url', models.URLField(blank=True, help_text='Paste the link to your fourth social media post', null=True, verbose_name='Channel 4 URL')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Social Media Channels',
                'verbose_name_plural': 'Social Media Channels',
            },
        ),
    ]
