# Generated by Django 4.2.16 on 2026-01-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='DEPRECATED: Use GlobalSettings instead.', null=True, verbose_name='Facebook URL (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='DEPRECATED: Use GlobalSettings instead.', null=True, verbose_name='Instagram URL (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='DEPRECATED: Use GlobalSettings instead.', null=True, verbose_name='LinkedIn URL (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='tiktok_url',
            field=models.URLField(blank=True, help_text='DEPRECATED: Use GlobalSettings instead.', null=True, verbose_name='TikTok URL (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='DEPRECATED: Use GlobalSettings instead.', null=True, verbose_name='Twitter URL (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='DEPRECATED: Use GlobalSettings instead.', null=True, verbose_name='YouTube URL (DEPRECATED)'),
        ),
    ]
