# Generated by Django 4.2.16 on 2026-01-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0002_alter_contactinformation_facebook_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpost',
            name='platform',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Twitter (X)', 'Twitter (X)'), ('TikTok', 'TikTok'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn'), ('YouTube', 'YouTube')], max_length=50, verbose_name='Platform'),
        ),
    ]
