# Generated by Django 4.2.16 on 2025-12-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0002_socialmediachannels'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_email', models.EmailField(blank=True, help_text='Main contact email (e.g., info@sauti.org)', max_length=254, null=True, verbose_name='Primary Email')),
                ('support_email', models.EmailField(blank=True, help_text='Support/help email (e.g., support@sauti.org)', max_length=254, null=True, verbose_name='Support Email')),
                ('primary_phone', models.CharField(blank=True, help_text='Main contact phone (e.g., +256 116 or 116)', max_length=50, null=True, verbose_name='Primary Phone')),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp contact number', max_length=50, null=True, verbose_name='WhatsApp Number')),
                ('office_address', models.TextField(blank=True, help_text='Physical office address', null=True, verbose_name='Office Address')),
                ('facebook_url', models.URLField(blank=True, help_text='Link to Facebook page', null=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, help_text='Link to Twitter/X profile', null=True, verbose_name='Twitter URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Link to Instagram profile', null=True, verbose_name='Instagram URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='Link to LinkedIn page', null=True, verbose_name='LinkedIn URL')),
                ('youtube_url', models.URLField(blank=True, help_text='Link to YouTube channel', null=True, verbose_name='YouTube URL')),
                ('tiktok_url', models.URLField(blank=True, help_text='Link to TikTok profile', null=True, verbose_name='TikTok URL')),
                ('working_hours', models.CharField(blank=True, help_text='e.g., 24/7 or Mon-Fri 8AM-5PM', max_length=100, null=True, verbose_name='Working Hours')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
    ]
