# Generated by Django 4.2.16 on 2026-01-03 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the timeline event', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the event')),
                ('date', models.DateField(help_text='Date of the event')),
                ('icon', models.CharField(blank=True, help_text='Icon name (e.g., Heroicon name) for this event', max_length=50, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this event is visible on the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Timeline Event',
                'verbose_name_plural': 'Timeline Events',
                'ordering': ['date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the team member', max_length=100)),
                ('role', models.CharField(help_text='Role or title of the team member', max_length=100)),
                ('bio', models.TextField(blank=True, help_text='Short biography of the team member', null=True)),
                ('image', models.ImageField(blank=True, help_text='Profile image of the team member', null=True, upload_to='team_members/')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this team member is visible on the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='Unique identifier for this content', max_length=100, unique=True)),
                ('label', models.CharField(help_text='Human readable label', max_length=200)),
                ('value', models.TextField(help_text='The actual content (text or image URL)')),
                ('type', models.CharField(choices=[('text', 'Text'), ('photo', 'Photo'), ('heading', 'Heading'), ('button', 'Button'), ('video', 'Video'), ('icon', 'Icon')], default='text', max_length=20)),
                ('page', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('operations', 'Operations'), ('blog', 'Blog'), ('resources', 'Resources'), ('faqs', 'FAQs'), ('partners', 'Partners'), ('contact', 'Contact'), ('donate', 'Donate'), ('reports', 'Reports'), ('header', 'Header'), ('footer', 'Footer')], default='home', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of where this content is used', null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Content',
                'verbose_name_plural': 'Site Content',
                'ordering': ['page', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ProtectionApproach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the approach section or step', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of this approach section')),
                ('icon', models.CharField(blank=True, help_text='Icon name (e.g., Heroicon name) for this approach section', max_length=50, null=True)),
                ('color', models.CharField(default='blue', help_text='Tailwind color class for styling (e.g., blue, teal, orange)', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this approach section is visible on the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Protection Approach',
                'verbose_name_plural': 'Protection Approaches',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Value title (e.g., Confidentiality)', max_length=100)),
                ('description', models.TextField(help_text='Description of this core value')),
                ('icon', models.CharField(blank=True, help_text='Icon name or SVG path identifier', max_length=50, null=True)),
                ('color_from', models.CharField(default='blue-500', help_text='Tailwind gradient start color (e.g., blue-500)', max_length=20)),
                ('color_to', models.CharField(default='blue-600', help_text='Tailwind gradient end color (e.g., blue-600)', max_length=20)),
                ('border_color', models.CharField(default='blue-100', help_text='Tailwind border color (e.g., blue-100)', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this value on the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Core Value',
                'verbose_name_plural': 'Core Values',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the contact item (e.g., 'Emergency Hotline', 'WhatsApp')", max_length=100)),
                ('value', models.CharField(help_text="The contact detail (e.g., '116', 'info@example.com', 'Street Address')", max_length=255)),
                ('type', models.CharField(choices=[('phone', 'Phone Number'), ('email', 'Email Address'), ('location', 'Physical Location'), ('social', 'Social Media Link'), ('other', 'Other')], default='phone', help_text='Type of contact information', max_length=20)),
                ('icon', models.CharField(blank=True, help_text="Name of the icon for the contact (e.g., 'phone', 'envelope', 'location-marker')", max_length=50, null=True)),
                ('order', models.IntegerField(default=0, help_text='Order in which the contact item appears')),
                ('is_visible', models.BooleanField(default=True, help_text='Whether this contact item should be visible on the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Item',
                'verbose_name_plural': 'Contact Items',
                'ordering': ['order', 'name'],
            },
        ),
    ]
