# Generated by Django 4.2.16 on 2025-12-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='Unique identifier for this content', max_length=100, unique=True)),
                ('label', models.CharField(help_text='Human readable label', max_length=200)),
                ('value', models.TextField(help_text='The actual content (text or image URL)')),
                ('type', models.CharField(choices=[('text', 'Text'), ('photo', 'Photo'), ('heading', 'Heading'), ('button', 'Button'), ('video', 'Video'), ('icon', 'Icon')], default='text', max_length=20)),
                ('page', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('operations', 'Operations'), ('blog', 'Blog'), ('resources', 'Resources'), ('faqs', 'FAQs'), ('partners', 'Partners'), ('contact', 'Contact'), ('donate', 'Donate'), ('reports', 'Reports'), ('header', 'Header'), ('footer', 'Footer')], default='home', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of where this content is used', null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Content',
                'verbose_name_plural': 'Site Content',
                'ordering': ['page', 'key'],
            },
        ),
    ]
