# Generated by Django 4.2.16 on 2025-12-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Value title (e.g., Confidentiality)', max_length=100)),
                ('description', models.TextField(help_text='Description of this core value')),
                ('icon', models.CharField(blank=True, help_text='Icon name or SVG path identifier', max_length=50, null=True)),
                ('color_from', models.CharField(default='blue-500', help_text='Tailwind gradient start color (e.g., blue-500)', max_length=20)),
                ('color_to', models.CharField(default='blue-600', help_text='Tailwind gradient end color (e.g., blue-600)', max_length=20)),
                ('border_color', models.CharField(default='blue-100', help_text='Tailwind border color (e.g., blue-100)', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this value on the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Core Value',
                'verbose_name_plural': 'Core Values',
                'ordering': ['order', 'title'],
            },
        ),
    ]
