# Generated by Django 4.2.16 on 2026-01-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('operations', 'Operations'), ('blog', 'Blog'), ('resources', 'Resources'), ('faqs', 'FAQs'), ('partners', 'Partners'), ('contact', 'Contact'), ('donate', 'Donate'), ('reports', 'Reports'), ('header', 'Header'), ('footer', 'Footer'), ('global', 'Global Settings')], default='home', max_length=50),
        ),
    ]
