# Generated by Django 4.2.16 on 2026-03-05 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0002_alter_sitecontent_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoWeAreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(choices=[(1, '1. Left Column - Top (Community)'), (2, '2. Left Column - Middle (Helpline)'), (3, '3. Left Column - Bottom (Family)'), (4, '4. Center Grid - Top Left (Team Photo)'), (5, '5. Center Grid - Top Right (Happy Students)'), (6, '6. Center Grid - Bottom Left (Action)'), (7, '7. Center Grid - Bottom Right (Protection)'), (8, '8. Right Column - Top (Operations)'), (9, '9. Right Column - Middle (Inclusive)')], help_text='Position in the hero grid layout', unique=True)),
                ('title', models.CharField(help_text="Short title describing this image (e.g., 'Community Support')", max_length=100)),
                ('image', models.ImageField(help_text='Image to display in this grid position (recommended: 800x600px)', upload_to='who_we_are/')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this image is displayed on the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Who We Are Image',
                'verbose_name_plural': 'Who We Are Images',
                'ordering': ['position'],
            },
        ),
    ]
