# Generated by Django 4.2.16 on 2025-12-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_corevalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the contact item (e.g., 'Emergency Hotline', 'WhatsApp')", max_length=100)),
                ('value', models.CharField(help_text="The contact detail (e.g., '116', 'info@example.com', 'Street Address')", max_length=255)),
                ('type', models.CharField(choices=[('phone', 'Phone Number'), ('email', 'Email Address'), ('location', 'Physical Location'), ('social', 'Social Media Link'), ('other', 'Other')], default='phone', help_text='Type of contact information', max_length=20)),
                ('icon', models.CharField(blank=True, help_text="Name of the icon for the contact (e.g., 'phone', 'envelope', 'location-marker')", max_length=50, null=True)),
                ('order', models.IntegerField(default=0, help_text='Order in which the contact item appears')),
                ('is_visible', models.BooleanField(default=True, help_text='Whether this contact item should be visible on the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Item',
                'verbose_name_plural': 'Contact Items',
                'ordering': ['order', 'name'],
            },
        ),
    ]
