# Generated by Django 4.2.16 on 2026-03-05 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0003_whoweareimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('journey_step_1', 'Journey Step 1 - Access'), ('journey_step_2', 'Journey Step 2 - Response'), ('journey_step_3', 'Journey Step 3 - Management'), ('journey_step_4', 'Journey Step 4 - Protection'), ('infrastructure', 'Infrastructure Section'), ('service_counseling', 'Service - Telephone Counseling'), ('service_walkin', 'Service - Walk-In Support'), ('service_media', 'Service - Media Response'), ('service_guidance', 'Service - Information & Guidance'), ('service_referral', 'Service - Essential Service Referrals'), ('service_community', 'Service - Community Sensitization')], help_text='Position/section where this image will be displayed', max_length=50, unique=True)),
                ('title', models.CharField(help_text='Short title describing this image', max_length=100)),
                ('image', models.ImageField(help_text='Image to display (recommended: 800x600px for services, 400x500px for journey)', upload_to='operations/')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this image is displayed on the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operations Page Image',
                'verbose_name_plural': 'Operations Page Images',
                'ordering': ['position'],
            },
        ),
    ]
