# Generated by Django 4.2.16 on 2025-12-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectionApproach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the approach section or step', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of this approach section')),
                ('icon', models.CharField(blank=True, help_text='Icon name (e.g., Heroicon name) for this approach section', max_length=50, null=True)),
                ('color', models.CharField(default='blue', help_text='Tailwind color class for styling (e.g., blue, teal, orange)', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this approach section is visible on the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Protection Approach',
                'verbose_name_plural': 'Protection Approaches',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the team member', max_length=100)),
                ('role', models.CharField(help_text='Role or title of the team member', max_length=100)),
                ('bio', models.TextField(blank=True, help_text='Short biography of the team member', null=True)),
                ('image', models.ImageField(blank=True, help_text='Profile image of the team member', null=True, upload_to='team_members/')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this team member is visible on the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
    ]
