# Generated by Django 4.2.16 on 2026-04-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_operationsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='description',
            field=models.CharField(blank=True, help_text='Short description of the contact channel', max_length=255, null=True),
        ),
    ]
