# Generated by Django 4.2.16 on 2025-12-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_protectionapproach_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the timeline event', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the event')),
                ('date', models.DateField(help_text='Date of the event')),
                ('icon', models.CharField(blank=True, help_text='Icon name (e.g., Heroicon name) for this event', max_length=50, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this event is visible on the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Timeline Event',
                'verbose_name_plural': 'Timeline Events',
                'ordering': ['date', 'order'],
            },
        ),
    ]
