# Generated by Django 4.2.16 on 2026-06-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_contact_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationsimage',
            name='position',
            field=models.CharField(choices=[('journey_step_1', 'Journey Step 1 - Access'), ('journey_step_2', 'Journey Step 2 - Response'), ('journey_step_3', 'Journey Step 3 - Management'), ('journey_step_4', 'Journey Step 4 - Protection'), ('infrastructure', 'Infrastructure Section'), ('service_counseling', 'Service - Telephone Counseling'), ('service_walkin', 'Service - Walk-In Support'), ('service_media', 'Service - Media Response'), ('service_guidance', 'Service - Information & Guidance'), ('service_referral', 'Service - Essential Service Referrals'), ('service_community', 'Service - Community Sensitization'), ('service_chatbot', 'Service - MHPSS Chatbot')], help_text='Position/section where this image will be displayed', max_length=50, unique=True),
        ),
    ]
