# Generated by Django 4.2.16 on 2026-07-22 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_operationsimage_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_values', to='content.contact')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
