# Generated by Django 4.2.16 on 2026-08-26 10:00
# Hand-written (no Django/DB available in this environment).
# Needs `python manage.py makemigrations --check` + `migrate` run for real.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_contactvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='image_thumbnail',
            field=models.ImageField(blank=True, editable=False, help_text='Auto-generated thumbnail derived from image', null=True, upload_to='team_members/thumbnails/'),
        ),
    ]
