# Generated by Django 5.1 on 2025-10-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CHILD_PROTECTION', 'Child Protection'), ('GBV', 'Gender-Based Violence'), ('MIGRANT', 'Migrant Worker'), ('PSEA', 'PSEA (Sexual Exploitation & Abuse)')], help_text='Type of report', max_length=20)),
                ('description', models.TextField(help_text='Description of the incident/case')),
                ('encrypted_description', models.TextField(blank=True, help_text='Encrypted version')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Report submitted anonymously')),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(blank=True, help_text='District/location', max_length=200)),
                ('attachment', models.FileField(blank=True, help_text='Optional evidence file', null=True, upload_to='reports/attachments/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='PENDING', max_length=15)),
                ('reference_number', models.CharField(blank=True, help_text='Auto-generated reference number', max_length=20, unique=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes (not visible to reporter)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken', models.TextField(help_text='Description of action taken')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Report Follow-up',
                'verbose_name_plural': 'Report Follow-ups',
                'ordering': ['-created_at'],
            },
        ),
    ]
