# Generated by Django 4.2.16 on 2026-01-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_self_report',
            field=models.BooleanField(default=None, help_text='True if reporting for self, False if reporting for another', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='reported_person_age',
            field=models.IntegerField(blank=True, help_text='Age of the victim/concerned person', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='reported_person_gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('UNKNOWN', 'Unknown')], help_text='Gender of the victim/concerned person', max_length=10, null=True),
        ),
    ]
