# Generated by Django 4.2.16 on 2026-01-03 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0003_report_is_self_report_report_reported_person_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalReport',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('category', models.CharField(choices=[('CHILD_PROTECTION', 'Child Protection'), ('GBV', 'Gender-Based Violence'), ('MIGRANT', 'Migrant Worker'), ('PSEA', 'PSEA (Sexual Exploitation & Abuse)')], help_text='Type of report', max_length=20)),
                ('description', models.TextField(help_text='Description of the incident/case')),
                ('encrypted_description', models.TextField(blank=True, help_text='Encrypted version')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Report submitted anonymously')),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(blank=True, help_text='District/location', max_length=200)),
                ('reported_person_age', models.IntegerField(blank=True, help_text='Age of the victim/concerned person', null=True)),
                ('reported_person_gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('UNKNOWN', 'Unknown')], help_text='Gender of the victim/concerned person', max_length=10, null=True)),
                ('is_self_report', models.BooleanField(default=None, help_text='True if reporting for self, False if reporting for another', null=True)),
                ('attachment', models.TextField(blank=True, help_text='Optional evidence file', max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='PENDING', max_length=15)),
                ('reference_number', models.CharField(blank=True, db_index=True, help_text='Auto-generated reference number', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes (not visible to reporter)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assigned_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical report',
                'verbose_name_plural': 'historical reports',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
