# Generated by Django 4.2.16 on 2026-01-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_historicalreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreport',
            name='reporting_for',
            field=models.CharField(choices=[('SELF', 'Self'), ('ADULT_OTHER', 'Adult (Other)'), ('CHILD', 'Child'), ('MULTIPLE', 'Multiple People'), ('UNSPECIFIED', 'Unspecified')], default='UNSPECIFIED', help_text='Who is the report being filed for?', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='reporting_for',
            field=models.CharField(choices=[('SELF', 'Self'), ('ADULT_OTHER', 'Adult (Other)'), ('CHILD', 'Child'), ('MULTIPLE', 'Multiple People'), ('UNSPECIFIED', 'Unspecified')], default='UNSPECIFIED', help_text='Who is the report being filed for?', max_length=20),
        ),
    ]
