# Generated by Django 4.2.16 on 2026-01-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_historicalreport_reporting_for_report_reporting_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreport',
            name='affected_persons',
            field=models.JSONField(blank=True, default=list, help_text='List of affected persons data from intake'),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='safe_to_contact',
            field=models.BooleanField(default=True, help_text='Is it safe to contact the reporter?'),
        ),
        migrations.AddField(
            model_name='report',
            name='affected_persons',
            field=models.JSONField(blank=True, default=list, help_text='List of affected persons data from intake'),
        ),
        migrations.AddField(
            model_name='report',
            name='safe_to_contact',
            field=models.BooleanField(default=True, help_text='Is it safe to contact the reporter?'),
        ),
    ]
