# Generated by Django 4.2.16 on 2026-01-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_historicalreport_affected_persons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreport',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='forwarded_to_openchs_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalreport',
            name='openchs_case_id',
            field=models.CharField(blank=True, help_text='ID from OpenCHS system', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='forwarded_to_openchs_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='openchs_case_id',
            field=models.CharField(blank=True, help_text='ID from OpenCHS system', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('IN_PROGRESS', 'In Progress'), ('ESCALATED', 'Escalated'), ('FORWARDED', 'Forwarded to OpenCHS'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('IN_PROGRESS', 'In Progress'), ('ESCALATED', 'Escalated'), ('FORWARDED', 'Forwarded to OpenCHS'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='PENDING', max_length=15),
        ),
    ]
